create table if not exists public."Announcement" (
    "announcementID" bigint generated by default as identity primary key,
    "userID" uuid not null references auth.users(id) on delete cascade,
    "categoryID" bigint references public."Category"("categoryID") on delete set null,
    title text not null,
    description text not null,
    "publishDate" date not null default current_date,
    "publishTime" time not null default current_time,
    status text not null default 'ACTIVE',
    created_at timestamptz not null default now()
);

alter table public."Announcement" enable row level security;

create policy "Anyone can read active announcements"
on public."Announcement"
for select
using (status = 'ACTIVE');

create policy "Authenticated users can create announcements"
on public."Announcement"
for insert
to authenticated
with check (auth.uid() = "userID");
